#############################################################################
# Makefile for building: libsst_dxf03_lib_d.a
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  sstDxf03Lib.pro
# Template: lib
# Command: /usr/lib/qt5/bin/qmake -o Makefile sstDxf03Lib.pro -spec linux-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_QML_DEBUG
CFLAGS        = -pipe -g -fPIC -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -fPIC -std=gnu++11 -Wall -W $(DEFINES)
INCPATH       = -I. -I../dxflib/src -I../sstLibreCAD2Lib/Header -I../sst_str01_lib/Header -I../sstMath01Lib/Header -I../sst_misc01_lib/Header -I../sst_rec04_lib/Header -IHeader -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = sst_dxf03_lib_d1.0.0
DISTDIR = /home/uli/Entwicklung/sst_dxf03_lib/.tmp/sst_dxf03_lib_d1.0.0
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Entities/sstDxf03Arc.cpp \
		Entities/sstDxf03Circle.cpp \
		Entities/sstDxf03Hatch.cpp \
		Entities/sstDxf03HatchEdge.cpp \
		Entities/sstDxf03HatchLoop.cpp \
		Entities/sstDxf03Insert.cpp \
		Entities/sstDxf03MText.cpp \
		Entities/sstDxf03Polyline.cpp \
		Entities/sstDxf03Text.cpp \
		Entities/sstDxf03Vertex.cpp \
		Entities/sstDxf03Point.cpp \
		Entities/sstDxf03Line.cpp \
		Tables/sstDxf03LType.cpp \
		sstDxf03Write.cpp \
		sstDxf03Read.cpp \
		sstDxf03Main.cpp \
		sstDxf03Layer.cpp \
		sstDxf03Database.cpp \
		sstDxf03EntityType.cpp \
		sstDxf03Base.cpp \
		sstDxf03Block.cpp \
		sstDxf03Lib.cpp \
		Entities/sstDxf03Trace.cpp 
OBJECTS       = sstDxf03Arc.o \
		sstDxf03Circle.o \
		sstDxf03Hatch.o \
		sstDxf03HatchEdge.o \
		sstDxf03HatchLoop.o \
		sstDxf03Insert.o \
		sstDxf03MText.o \
		sstDxf03Polyline.o \
		sstDxf03Text.o \
		sstDxf03Vertex.o \
		sstDxf03Point.o \
		sstDxf03Line.o \
		sstDxf03LType.o \
		sstDxf03Write.o \
		sstDxf03Read.o \
		sstDxf03Main.o \
		sstDxf03Layer.o \
		sstDxf03Database.o \
		sstDxf03EntityType.o \
		sstDxf03Base.o \
		sstDxf03Block.o \
		sstDxf03Lib.o \
		sstDxf03Trace.o
DIST          = sstDxf03Lib.odt \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/clang.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		sstDxf03Lib.pro ./Header/sstDxf03Lib.h \
		+= \
		sstDxf03LibInt.h Entities/sstDxf03Arc.cpp \
		Entities/sstDxf03Circle.cpp \
		Entities/sstDxf03Hatch.cpp \
		Entities/sstDxf03HatchEdge.cpp \
		Entities/sstDxf03HatchLoop.cpp \
		Entities/sstDxf03Insert.cpp \
		Entities/sstDxf03MText.cpp \
		Entities/sstDxf03Polyline.cpp \
		Entities/sstDxf03Text.cpp \
		Entities/sstDxf03Vertex.cpp \
		Entities/sstDxf03Point.cpp \
		Entities/sstDxf03Line.cpp \
		Tables/sstDxf03LType.cpp \
		sstDxf03Write.cpp \
		sstDxf03Read.cpp \
		sstDxf03Main.cpp \
		sstDxf03Layer.cpp \
		sstDxf03Database.cpp \
		sstDxf03EntityType.cpp \
		sstDxf03Base.cpp \
		sstDxf03Block.cpp \
		sstDxf03Lib.cpp \
		Entities/sstDxf03Trace.cpp
QMAKE_TARGET  = sst_dxf03_lib_d
DESTDIR       = ../libs/
TARGET        = libsst_dxf03_lib_d.a


first: all
####### Build rules

staticlib: ../libs/$(TARGET)

../libs/$(TARGET):  $(OBJECTS) $(OBJCOMP) 
	@test -d ../libs/ || mkdir -p ../libs/
	-$(DEL_FILE) ../libs/$(TARGET)
	$(AR) $(DESTDIR)$(TARGET) $(OBJECTS)


Makefile: sstDxf03Lib.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/clang.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		sstDxf03Lib.pro
	$(QMAKE) -o Makefile sstDxf03Lib.pro -spec linux-clang CONFIG+=debug CONFIG+=qml_debug
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/clang.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
sstDxf03Lib.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile sstDxf03Lib.pro -spec linux-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile ../libs/$(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) ../libs/$(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

sstDxf03Arc.o: Entities/sstDxf03Arc.cpp ../dxflib/src/dl_dxf.h \
		../dxflib/src/dl_global.h \
		../dxflib/src/dl_attributes.h \
		../dxflib/src/dl_codes.h \
		../dxflib/src/dl_entities.h \
		../dxflib/src/dl_writer_ascii.h \
		../dxflib/src/dl_writer.h \
		../dxflib/src/dl_creationadapter.h \
		../dxflib/src/dl_creationinterface.h \
		../dxflib/src/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Arc.o Entities/sstDxf03Arc.cpp

sstDxf03Circle.o: Entities/sstDxf03Circle.cpp ../dxflib/src/dl_dxf.h \
		../dxflib/src/dl_global.h \
		../dxflib/src/dl_attributes.h \
		../dxflib/src/dl_codes.h \
		../dxflib/src/dl_entities.h \
		../dxflib/src/dl_writer_ascii.h \
		../dxflib/src/dl_writer.h \
		../dxflib/src/dl_creationadapter.h \
		../dxflib/src/dl_creationinterface.h \
		../dxflib/src/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Circle.o Entities/sstDxf03Circle.cpp

sstDxf03Hatch.o: Entities/sstDxf03Hatch.cpp ../dxflib/src/dl_dxf.h \
		../dxflib/src/dl_global.h \
		../dxflib/src/dl_attributes.h \
		../dxflib/src/dl_codes.h \
		../dxflib/src/dl_entities.h \
		../dxflib/src/dl_writer_ascii.h \
		../dxflib/src/dl_writer.h \
		../dxflib/src/dl_creationadapter.h \
		../dxflib/src/dl_creationinterface.h \
		../dxflib/src/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Hatch.o Entities/sstDxf03Hatch.cpp

sstDxf03HatchEdge.o: Entities/sstDxf03HatchEdge.cpp ../dxflib/src/dl_dxf.h \
		../dxflib/src/dl_global.h \
		../dxflib/src/dl_attributes.h \
		../dxflib/src/dl_codes.h \
		../dxflib/src/dl_entities.h \
		../dxflib/src/dl_writer_ascii.h \
		../dxflib/src/dl_writer.h \
		../dxflib/src/dl_creationadapter.h \
		../dxflib/src/dl_creationinterface.h \
		../dxflib/src/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03HatchEdge.o Entities/sstDxf03HatchEdge.cpp

sstDxf03HatchLoop.o: Entities/sstDxf03HatchLoop.cpp ../dxflib/src/dl_dxf.h \
		../dxflib/src/dl_global.h \
		../dxflib/src/dl_attributes.h \
		../dxflib/src/dl_codes.h \
		../dxflib/src/dl_entities.h \
		../dxflib/src/dl_writer_ascii.h \
		../dxflib/src/dl_writer.h \
		../dxflib/src/dl_creationadapter.h \
		../dxflib/src/dl_creationinterface.h \
		../dxflib/src/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03HatchLoop.o Entities/sstDxf03HatchLoop.cpp

sstDxf03Insert.o: Entities/sstDxf03Insert.cpp ../dxflib/src/dl_dxf.h \
		../dxflib/src/dl_global.h \
		../dxflib/src/dl_attributes.h \
		../dxflib/src/dl_codes.h \
		../dxflib/src/dl_entities.h \
		../dxflib/src/dl_writer_ascii.h \
		../dxflib/src/dl_writer.h \
		../dxflib/src/dl_creationadapter.h \
		../dxflib/src/dl_creationinterface.h \
		../dxflib/src/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Insert.o Entities/sstDxf03Insert.cpp

sstDxf03MText.o: Entities/sstDxf03MText.cpp ../dxflib/src/dl_dxf.h \
		../dxflib/src/dl_global.h \
		../dxflib/src/dl_attributes.h \
		../dxflib/src/dl_codes.h \
		../dxflib/src/dl_entities.h \
		../dxflib/src/dl_writer_ascii.h \
		../dxflib/src/dl_writer.h \
		../dxflib/src/dl_creationadapter.h \
		../dxflib/src/dl_creationinterface.h \
		../dxflib/src/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03MText.o Entities/sstDxf03MText.cpp

sstDxf03Polyline.o: Entities/sstDxf03Polyline.cpp ../dxflib/src/dl_dxf.h \
		../dxflib/src/dl_global.h \
		../dxflib/src/dl_attributes.h \
		../dxflib/src/dl_codes.h \
		../dxflib/src/dl_entities.h \
		../dxflib/src/dl_writer_ascii.h \
		../dxflib/src/dl_writer.h \
		../dxflib/src/dl_creationadapter.h \
		../dxflib/src/dl_creationinterface.h \
		../dxflib/src/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Polyline.o Entities/sstDxf03Polyline.cpp

sstDxf03Text.o: Entities/sstDxf03Text.cpp ../dxflib/src/dl_dxf.h \
		../dxflib/src/dl_global.h \
		../dxflib/src/dl_attributes.h \
		../dxflib/src/dl_codes.h \
		../dxflib/src/dl_entities.h \
		../dxflib/src/dl_writer_ascii.h \
		../dxflib/src/dl_writer.h \
		../dxflib/src/dl_creationadapter.h \
		../dxflib/src/dl_creationinterface.h \
		../dxflib/src/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Text.o Entities/sstDxf03Text.cpp

sstDxf03Vertex.o: Entities/sstDxf03Vertex.cpp ../dxflib/src/dl_dxf.h \
		../dxflib/src/dl_global.h \
		../dxflib/src/dl_attributes.h \
		../dxflib/src/dl_codes.h \
		../dxflib/src/dl_entities.h \
		../dxflib/src/dl_writer_ascii.h \
		../dxflib/src/dl_writer.h \
		../dxflib/src/dl_creationadapter.h \
		../dxflib/src/dl_creationinterface.h \
		../dxflib/src/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Vertex.o Entities/sstDxf03Vertex.cpp

sstDxf03Point.o: Entities/sstDxf03Point.cpp ../dxflib/src/dl_dxf.h \
		../dxflib/src/dl_global.h \
		../dxflib/src/dl_attributes.h \
		../dxflib/src/dl_codes.h \
		../dxflib/src/dl_entities.h \
		../dxflib/src/dl_writer_ascii.h \
		../dxflib/src/dl_writer.h \
		../dxflib/src/dl_creationadapter.h \
		../dxflib/src/dl_creationinterface.h \
		../dxflib/src/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Point.o Entities/sstDxf03Point.cpp

sstDxf03Line.o: Entities/sstDxf03Line.cpp ../dxflib/src/dl_dxf.h \
		../dxflib/src/dl_global.h \
		../dxflib/src/dl_attributes.h \
		../dxflib/src/dl_codes.h \
		../dxflib/src/dl_entities.h \
		../dxflib/src/dl_writer_ascii.h \
		../dxflib/src/dl_writer.h \
		../dxflib/src/dl_creationadapter.h \
		../dxflib/src/dl_creationinterface.h \
		../dxflib/src/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Line.o Entities/sstDxf03Line.cpp

sstDxf03LType.o: Tables/sstDxf03LType.cpp ../dxflib/src/dl_dxf.h \
		../dxflib/src/dl_global.h \
		../dxflib/src/dl_attributes.h \
		../dxflib/src/dl_codes.h \
		../dxflib/src/dl_entities.h \
		../dxflib/src/dl_writer_ascii.h \
		../dxflib/src/dl_writer.h \
		../dxflib/src/dl_creationadapter.h \
		../dxflib/src/dl_creationinterface.h \
		../dxflib/src/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03LType.o Tables/sstDxf03LType.cpp

sstDxf03Write.o: sstDxf03Write.cpp ../dxflib/src/dl_dxf.h \
		../dxflib/src/dl_global.h \
		../dxflib/src/dl_attributes.h \
		../dxflib/src/dl_codes.h \
		../dxflib/src/dl_entities.h \
		../dxflib/src/dl_writer_ascii.h \
		../dxflib/src/dl_writer.h \
		../dxflib/src/dl_creationadapter.h \
		../dxflib/src/dl_creationinterface.h \
		../dxflib/src/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Write.o sstDxf03Write.cpp

sstDxf03Read.o: sstDxf03Read.cpp ../dxflib/src/dl_dxf.h \
		../dxflib/src/dl_global.h \
		../dxflib/src/dl_attributes.h \
		../dxflib/src/dl_codes.h \
		../dxflib/src/dl_entities.h \
		../dxflib/src/dl_writer_ascii.h \
		../dxflib/src/dl_writer.h \
		../dxflib/src/dl_creationadapter.h \
		../dxflib/src/dl_creationinterface.h \
		../dxflib/src/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Read.o sstDxf03Read.cpp

sstDxf03Main.o: sstDxf03Main.cpp ../dxflib/src/dl_dxf.h \
		../dxflib/src/dl_global.h \
		../dxflib/src/dl_attributes.h \
		../dxflib/src/dl_codes.h \
		../dxflib/src/dl_entities.h \
		../dxflib/src/dl_writer_ascii.h \
		../dxflib/src/dl_writer.h \
		../dxflib/src/dl_creationadapter.h \
		../dxflib/src/dl_creationinterface.h \
		../dxflib/src/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Main.o sstDxf03Main.cpp

sstDxf03Layer.o: sstDxf03Layer.cpp ../dxflib/src/dl_dxf.h \
		../dxflib/src/dl_global.h \
		../dxflib/src/dl_attributes.h \
		../dxflib/src/dl_codes.h \
		../dxflib/src/dl_entities.h \
		../dxflib/src/dl_writer_ascii.h \
		../dxflib/src/dl_writer.h \
		../dxflib/src/dl_creationadapter.h \
		../dxflib/src/dl_creationinterface.h \
		../dxflib/src/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Layer.o sstDxf03Layer.cpp

sstDxf03Database.o: sstDxf03Database.cpp ../dxflib/src/dl_dxf.h \
		../dxflib/src/dl_global.h \
		../dxflib/src/dl_attributes.h \
		../dxflib/src/dl_codes.h \
		../dxflib/src/dl_entities.h \
		../dxflib/src/dl_writer_ascii.h \
		../dxflib/src/dl_writer.h \
		../dxflib/src/dl_creationadapter.h \
		../dxflib/src/dl_creationinterface.h \
		../dxflib/src/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Database.o sstDxf03Database.cpp

sstDxf03EntityType.o: sstDxf03EntityType.cpp ../dxflib/src/dl_dxf.h \
		../dxflib/src/dl_global.h \
		../dxflib/src/dl_attributes.h \
		../dxflib/src/dl_codes.h \
		../dxflib/src/dl_entities.h \
		../dxflib/src/dl_writer_ascii.h \
		../dxflib/src/dl_writer.h \
		../dxflib/src/dl_creationadapter.h \
		../dxflib/src/dl_creationinterface.h \
		../dxflib/src/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03EntityType.o sstDxf03EntityType.cpp

sstDxf03Base.o: sstDxf03Base.cpp ../dxflib/src/dl_dxf.h \
		../dxflib/src/dl_global.h \
		../dxflib/src/dl_attributes.h \
		../dxflib/src/dl_codes.h \
		../dxflib/src/dl_entities.h \
		../dxflib/src/dl_writer_ascii.h \
		../dxflib/src/dl_writer.h \
		../dxflib/src/dl_creationadapter.h \
		../dxflib/src/dl_creationinterface.h \
		../dxflib/src/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Base.o sstDxf03Base.cpp

sstDxf03Block.o: sstDxf03Block.cpp ../dxflib/src/dl_dxf.h \
		../dxflib/src/dl_global.h \
		../dxflib/src/dl_attributes.h \
		../dxflib/src/dl_codes.h \
		../dxflib/src/dl_entities.h \
		../dxflib/src/dl_writer_ascii.h \
		../dxflib/src/dl_writer.h \
		../dxflib/src/dl_creationadapter.h \
		../dxflib/src/dl_creationinterface.h \
		../dxflib/src/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Block.o sstDxf03Block.cpp

sstDxf03Lib.o: sstDxf03Lib.cpp ../dxflib/src/dl_dxf.h \
		../dxflib/src/dl_global.h \
		../dxflib/src/dl_attributes.h \
		../dxflib/src/dl_codes.h \
		../dxflib/src/dl_entities.h \
		../dxflib/src/dl_writer_ascii.h \
		../dxflib/src/dl_writer.h \
		../dxflib/src/dl_creationadapter.h \
		../dxflib/src/dl_creationinterface.h \
		../dxflib/src/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Lib.o sstDxf03Lib.cpp

sstDxf03Trace.o: Entities/sstDxf03Trace.cpp ../dxflib/src/dl_dxf.h \
		../dxflib/src/dl_global.h \
		../dxflib/src/dl_attributes.h \
		../dxflib/src/dl_codes.h \
		../dxflib/src/dl_entities.h \
		../dxflib/src/dl_writer_ascii.h \
		../dxflib/src/dl_writer.h \
		../dxflib/src/dl_creationadapter.h \
		../dxflib/src/dl_creationinterface.h \
		../dxflib/src/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Trace.o Entities/sstDxf03Trace.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

