#############################################################################
# Makefile for building: libsst_dxf03_lib_d.a
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  sstDxf03Lib.pro
# Template: lib
# Command: /usr/lib/i386-linux-gnu/qt5/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile sstDxf03Lib.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -g -fPIC -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -fPIC -std=c++0x -Wall -W $(DEFINES)
INCPATH       = -I. -I../dxflib/Header -I../sstLibreCAD2Lib/Header -I../sst_str01_lib/Header -I../sstMath01Lib/Header -I../sst_misc01_lib/Header -I../sst_rec04_lib/Header -IHeader -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/i386-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = sst_dxf03_lib_d1.0.0
DISTDIR = /home/uli-le/Entwicklung/sst_dxf03_lib/.tmp/sst_dxf03_lib_d1.0.0
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Entities/sstDxf03Arc.cpp \
		Entities/sstDxf03Circle.cpp \
		Entities/sstDxf03Hatch.cpp \
		Entities/sstDxf03HatchEdge.cpp \
		Entities/sstDxf03HatchLoop.cpp \
		Entities/sstDxf03Insert.cpp \
		Entities/sstDxf03MText.cpp \
		Entities/sstDxf03Polyline.cpp \
		Entities/sstDxf03Text.cpp \
		Entities/sstDxf03Vertex.cpp \
		Entities/sstDxf03Point.cpp \
		Entities/sstDxf03Line.cpp \
		Tables/sstDxf03LType.cpp \
		sstDxf03Write.cpp \
		sstDxf03Read.cpp \
		sstDxf03Main.cpp \
		sstDxf03Layer.cpp \
		sstDxf03Database.cpp \
		sstDxf03EntityType.cpp \
		sstDxf03Base.cpp \
		sstDxf03Block.cpp \
		sstDxf03Lib.cpp \
		Entities/sstDxf03Trace.cpp 
OBJECTS       = sstDxf03Arc.o \
		sstDxf03Circle.o \
		sstDxf03Hatch.o \
		sstDxf03HatchEdge.o \
		sstDxf03HatchLoop.o \
		sstDxf03Insert.o \
		sstDxf03MText.o \
		sstDxf03Polyline.o \
		sstDxf03Text.o \
		sstDxf03Vertex.o \
		sstDxf03Point.o \
		sstDxf03Line.o \
		sstDxf03LType.o \
		sstDxf03Write.o \
		sstDxf03Read.o \
		sstDxf03Main.o \
		sstDxf03Layer.o \
		sstDxf03Database.o \
		sstDxf03EntityType.o \
		sstDxf03Base.o \
		sstDxf03Block.o \
		sstDxf03Lib.o \
		sstDxf03Trace.o
DIST          = /usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/lex.prf \
		sstDxf03Lib.pro ./Header/sstDxf03Lib.h \
		+= \
		sstDxf03LibInt.h Entities/sstDxf03Arc.cpp \
		Entities/sstDxf03Circle.cpp \
		Entities/sstDxf03Hatch.cpp \
		Entities/sstDxf03HatchEdge.cpp \
		Entities/sstDxf03HatchLoop.cpp \
		Entities/sstDxf03Insert.cpp \
		Entities/sstDxf03MText.cpp \
		Entities/sstDxf03Polyline.cpp \
		Entities/sstDxf03Text.cpp \
		Entities/sstDxf03Vertex.cpp \
		Entities/sstDxf03Point.cpp \
		Entities/sstDxf03Line.cpp \
		Tables/sstDxf03LType.cpp \
		sstDxf03Write.cpp \
		sstDxf03Read.cpp \
		sstDxf03Main.cpp \
		sstDxf03Layer.cpp \
		sstDxf03Database.cpp \
		sstDxf03EntityType.cpp \
		sstDxf03Base.cpp \
		sstDxf03Block.cpp \
		sstDxf03Lib.cpp \
		Entities/sstDxf03Trace.cpp
QMAKE_TARGET  = sst_dxf03_lib_d
DESTDIR       = ../libs/#avoid trailing-slash linebreak
TARGET        = libsst_dxf03_lib_d.a


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

staticlib: ../libs/$(TARGET)

../libs/$(TARGET):  $(OBJECTS) $(OBJCOMP) 
	@test -d ../libs/ || mkdir -p ../libs/
	-$(DEL_FILE) $(TARGET)
	$(AR) $(TARGET) $(OBJECTS)
	-$(DEL_FILE) ../libs/$(TARGET)
	-$(MOVE) $(TARGET) ../libs/ 


Makefile: sstDxf03Lib.pro /usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/lex.prf \
		sstDxf03Lib.pro
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile sstDxf03Lib.pro
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/c++11.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/lex.prf:
sstDxf03Lib.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile sstDxf03Lib.pro

qmake_all: FORCE


all: Makefile ../libs/$(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) ../libs/$(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

sstDxf03Arc.o: Entities/sstDxf03Arc.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Arc.o Entities/sstDxf03Arc.cpp

sstDxf03Circle.o: Entities/sstDxf03Circle.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Circle.o Entities/sstDxf03Circle.cpp

sstDxf03Hatch.o: Entities/sstDxf03Hatch.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Hatch.o Entities/sstDxf03Hatch.cpp

sstDxf03HatchEdge.o: Entities/sstDxf03HatchEdge.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03HatchEdge.o Entities/sstDxf03HatchEdge.cpp

sstDxf03HatchLoop.o: Entities/sstDxf03HatchLoop.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03HatchLoop.o Entities/sstDxf03HatchLoop.cpp

sstDxf03Insert.o: Entities/sstDxf03Insert.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Insert.o Entities/sstDxf03Insert.cpp

sstDxf03MText.o: Entities/sstDxf03MText.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03MText.o Entities/sstDxf03MText.cpp

sstDxf03Polyline.o: Entities/sstDxf03Polyline.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Polyline.o Entities/sstDxf03Polyline.cpp

sstDxf03Text.o: Entities/sstDxf03Text.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Text.o Entities/sstDxf03Text.cpp

sstDxf03Vertex.o: Entities/sstDxf03Vertex.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Vertex.o Entities/sstDxf03Vertex.cpp

sstDxf03Point.o: Entities/sstDxf03Point.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Point.o Entities/sstDxf03Point.cpp

sstDxf03Line.o: Entities/sstDxf03Line.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Line.o Entities/sstDxf03Line.cpp

sstDxf03LType.o: Tables/sstDxf03LType.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03LType.o Tables/sstDxf03LType.cpp

sstDxf03Write.o: sstDxf03Write.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Write.o sstDxf03Write.cpp

sstDxf03Read.o: sstDxf03Read.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Read.o sstDxf03Read.cpp

sstDxf03Main.o: sstDxf03Main.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Main.o sstDxf03Main.cpp

sstDxf03Layer.o: sstDxf03Layer.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Layer.o sstDxf03Layer.cpp

sstDxf03Database.o: sstDxf03Database.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Database.o sstDxf03Database.cpp

sstDxf03EntityType.o: sstDxf03EntityType.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03EntityType.o sstDxf03EntityType.cpp

sstDxf03Base.o: sstDxf03Base.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Base.o sstDxf03Base.cpp

sstDxf03Block.o: sstDxf03Block.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Block.o sstDxf03Block.cpp

sstDxf03Lib.o: sstDxf03Lib.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Lib.o sstDxf03Lib.cpp

sstDxf03Trace.o: Entities/sstDxf03Trace.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sstMath01Lib/Header/sstMath01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf03Lib.h \
		sstDxf03LibInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf03Trace.o Entities/sstDxf03Trace.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

